"""SQLAlchemy Core mirrors for AI Conversation Fabric schemas.

Schemas under schemas/objects remain authoritative; this module only provides
transactional Core table objects for engine.fabric services.
"""

from __future__ import annotations

from sqlalchemy import (
    TIMESTAMP,
    Boolean,
    Column,
    Integer,
    MetaData,
    Numeric,
    Table,
    Text,
    Uuid,
)
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

ai_conversation_policies = Table(
    "ai_conversation_policies",
    metadata,
    Column("policy_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("name", Text, nullable=False),
    Column("reasoning_effort", Text, nullable=False),
    Column("permission_profile", Text, nullable=False),
    Column("toolset_ids", JSONB, nullable=False),
    Column("allowed_capability_ids", JSONB, nullable=False),
    Column("denied_capability_ids", JSONB, nullable=False),
    Column("fallback_chain", JSONB, nullable=False),
    Column("max_turns", Integer, nullable=True),
    Column("context_token_budget", Integer, nullable=False),
    Column("cost_budget_usd", Numeric, nullable=True),
    Column("quality_priority", Integer, nullable=False),
    Column("latency_priority", Integer, nullable=False),
    Column("independent_review_required", Boolean, nullable=False),
    Column("created_by", Uuid(as_uuid=True), nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

agent_interop_endpoints = Table(
    "agent_interop_endpoints",
    metadata,
    Column("endpoint_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("harness_id", Text, nullable=False),
    Column("protocol", Text, nullable=False),
    Column("executable_or_uri", Text, nullable=False),
    Column("installation_version", Text, nullable=True),
    Column("discovery_state", Text, nullable=False),
    Column("certification_state", Text, nullable=False),
    Column("discovered_capabilities", JSONB, nullable=False),
    Column("certified_capabilities", JSONB, nullable=False),
    Column("certification_refs", JSONB, nullable=False),
    Column("health_state", Text, nullable=False),
    Column("config_hash", Text, nullable=True),
    Column("last_probe_at", TIMESTAMP(timezone=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

worker_sessions = Table(
    "worker_sessions",
    metadata,
    Column("worker_session_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=True),
    Column("task_id", Uuid(as_uuid=True), nullable=True),
    Column("endpoint_id", Uuid(as_uuid=True), nullable=False),
    Column("worker_profile_id", Text, nullable=True),
    Column("provider_session_ref", Text, nullable=True),
    Column("requested_model_id", Text, nullable=True),
    Column("serving_model_id", Text, nullable=True),
    Column("workspace_id", Uuid(as_uuid=True), nullable=True),
    Column("state", Text, nullable=False),
    Column("capability_snapshot", JSONB, nullable=False),
    Column("context_package_hash", Text, nullable=True),
    Column("tool_policy_hash", Text, nullable=True),
    Column("session_config_hash", Text, nullable=False),
    Column("parent_session_id", Uuid(as_uuid=True), nullable=True),
    Column("forked_from_session_id", Uuid(as_uuid=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("last_activity_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

provider_capacity_snapshots = Table(
    "provider_capacity_snapshots",
    metadata,
    Column("snapshot_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("endpoint_id", Uuid(as_uuid=True), nullable=False),
    Column("provider_id", Text, nullable=False),
    Column("state", Text, nullable=False),
    Column("reset_at", TIMESTAMP(timezone=True), nullable=True),
    Column("reset_source", Text, nullable=True),
    Column("confidence", Numeric, nullable=False),
    Column("active_concurrency", Integer, nullable=True),
    Column("max_concurrency", Integer, nullable=True),
    Column("latency_ms", Integer, nullable=True),
    Column("recent_failures", Integer, nullable=False),
    Column("input_cost_per_million", Numeric, nullable=True),
    Column("output_cost_per_million", Numeric, nullable=True),
    Column("quota_metadata", JSONB, nullable=False),
    Column("observed_at", TIMESTAMP(timezone=True), nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_provider_invocations = Table(
    "ai_provider_invocations",
    metadata,
    Column("invocation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("turn_id", Uuid(as_uuid=True), nullable=True),
    Column("worker_session_id", Uuid(as_uuid=True), nullable=True),
    Column("endpoint_id", Uuid(as_uuid=True), nullable=False),
    Column("fallback_parent_id", Uuid(as_uuid=True), nullable=True),
    Column("requested_profile_id", Text, nullable=True),
    Column("requested_model_id", Text, nullable=True),
    Column("serving_model_id", Text, nullable=True),
    Column("reasoning_effort", Text, nullable=False),
    Column("state", Text, nullable=False),
    Column("prompt_hash", Text, nullable=False),
    Column("context_hash", Text, nullable=False),
    Column("policy_hash", Text, nullable=False),
    Column("approval_id", Uuid(as_uuid=True), nullable=True),
    Column("worker_run_id", Uuid(as_uuid=True), nullable=True),
    Column("input_tokens", Integer, nullable=True),
    Column("output_tokens", Integer, nullable=True),
    Column("cache_tokens", Integer, nullable=True),
    Column("reasoning_tokens", Integer, nullable=True),
    Column("cost_usd", Numeric, nullable=True),
    Column("latency_ms", Integer, nullable=True),
    Column("result_refs", JSONB, nullable=False),
    Column("error_code", Text, nullable=True),
    Column("error_detail", Text, nullable=True),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("started_at", TIMESTAMP(timezone=True), nullable=True),
    Column("completed_at", TIMESTAMP(timezone=True), nullable=True),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_memory_items = Table(
    "ai_memory_items",
    metadata,
    Column("memory_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("scope_kind", Text, nullable=False),
    Column("scope_ref", Text, nullable=False),
    Column("trust_class", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("content", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("content_size_bytes", Integer, nullable=False),
    Column("token_estimate", Integer, nullable=False),
    Column("storage_backend", Text, nullable=False),
    Column("storage_key", Text, nullable=True),
    Column("source_type", Text, nullable=False),
    Column("source_refs", JSONB, nullable=False),
    Column("proposed_by_profile_id", Text, nullable=True),
    Column("approved_by", Uuid(as_uuid=True), nullable=True),
    Column("approved_at", TIMESTAMP(timezone=True), nullable=True),
    Column("supersedes_memory_id", Uuid(as_uuid=True), nullable=True),
    Column("fresh_until", TIMESTAMP(timezone=True), nullable=True),
    Column("metadata", JSONB, nullable=False),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_context_snapshots = Table(
    "ai_context_snapshots",
    metadata,
    Column("context_snapshot_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("turn_id", Uuid(as_uuid=True), nullable=True),
    Column("predecessor_snapshot_id", Uuid(as_uuid=True), nullable=True),
    Column("reason", Text, nullable=False),
    Column("summary", Text, nullable=True),
    Column("retained_refs", JSONB, nullable=False),
    Column("omitted_refs", JSONB, nullable=False),
    Column("omission_reasons", JSONB, nullable=False),
    Column("item_manifest", JSONB, nullable=False),
    Column("estimated_tokens", Integer, nullable=False),
    Column("budget_tokens", Integer, nullable=False),
    Column("context_hash", Text, nullable=False),
    Column("archive_storage_backend", Text, nullable=True),
    Column("archive_storage_key", Text, nullable=True),
    Column("archive_hash", Text, nullable=True),
    Column("archive_size_bytes", Integer, nullable=True),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_skills = Table(
    "ai_skills",
    metadata,
    Column("skill_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("slug", Text, nullable=False),
    Column("version", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("instructions", Text, nullable=False),
    Column("source_kind", Text, nullable=False),
    Column("source_ref", Text, nullable=True),
    Column("provenance_refs", JSONB, nullable=False),
    Column("license", Text, nullable=True),
    Column("manifest_hash", Text, nullable=False),
    Column("required_capability_ids", JSONB, nullable=False),
    Column("toolset_ids", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("evaluation_refs", JSONB, nullable=False),
    Column("certified_by", Uuid(as_uuid=True), nullable=True),
    Column("certified_at", TIMESTAMP(timezone=True), nullable=True),
    Column("parent_skill_id", Uuid(as_uuid=True), nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_agent_teams = Table(
    "ai_agent_teams",
    metadata,
    Column("team_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=True),
    Column("strategy", Text, nullable=False),
    Column("state", Text, nullable=False),
    Column("manager_profile_id", Text, nullable=True),
    Column("max_depth", Integer, nullable=False),
    Column("max_children", Integer, nullable=False),
    Column("aggregate_budget", JSONB, nullable=False),
    Column("members", JSONB, nullable=False),
    Column("result_refs", JSONB, nullable=False),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_research_artifacts = Table(
    "ai_research_artifacts",
    metadata,
    Column("research_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=True),
    Column("created_from_turn_id", Uuid(as_uuid=True), nullable=True),
    Column("mode", Text, nullable=False),
    Column("question", Text, nullable=False),
    Column("scope", JSONB, nullable=False),
    Column("state", Text, nullable=False),
    Column("source_ledger", JSONB, nullable=False),
    Column("findings", JSONB, nullable=False),
    Column("hypotheses", JSONB, nullable=False),
    Column("unresolved_questions", JSONB, nullable=False),
    Column("confidence", Numeric, nullable=True),
    Column("result_refs", JSONB, nullable=False),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_automations = Table(
    "ai_automations",
    metadata,
    Column("automation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=True),
    Column("name", Text, nullable=False),
    Column("schedule_kind", Text, nullable=False),
    Column("schedule_expression", Text, nullable=False),
    Column("timezone", Text, nullable=False),
    Column("action_kind", Text, nullable=False),
    Column("action_payload", JSONB, nullable=False),
    Column("state", Text, nullable=False),
    Column("next_run_at", TIMESTAMP(timezone=True), nullable=True),
    Column("last_run_at", TIMESTAMP(timezone=True), nullable=True),
    Column("last_result_ref", Text, nullable=True),
    Column("run_count", Integer, nullable=False),
    Column("created_by", Uuid(as_uuid=True), nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_hooks = Table(
    "ai_hooks",
    metadata,
    Column("hook_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=True),
    Column("name", Text, nullable=False),
    Column("event_kind", Text, nullable=False),
    Column("action_kind", Text, nullable=False),
    Column("condition", JSONB, nullable=False),
    Column("action_payload", JSONB, nullable=False),
    Column("state", Text, nullable=False),
    Column("last_triggered_at", TIMESTAMP(timezone=True), nullable=True),
    Column("trigger_count", Integer, nullable=False),
    Column("created_by", Uuid(as_uuid=True), nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

ai_claims = Table(
    "ai_claims",
    metadata,
    Column("claim_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("conversation_id", Uuid(as_uuid=True), nullable=False),
    Column("turn_id", Uuid(as_uuid=True), nullable=False),
    Column("claim_text", Text, nullable=False),
    Column("epistemic_class", Text, nullable=False),
    Column("confidence", Numeric, nullable=True),
    Column("source_refs", JSONB, nullable=False),
    Column("verification_state", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

experience_records = Table(
    "experience_records",
    metadata,
    Column("experience_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=True),
    Column("task_id", Uuid(as_uuid=True), nullable=True),
    Column("worker_run_id", Uuid(as_uuid=True), nullable=True),
    Column("worker_session_id", Uuid(as_uuid=True), nullable=True),
    Column("task_signature", JSONB, nullable=False),
    Column("worker_configuration", JSONB, nullable=False),
    Column("outcome", JSONB, nullable=False),
    Column("economics", JSONB, nullable=False),
    Column("failure_signatures", JSONB, nullable=False),
    Column("verification_refs", JSONB, nullable=False),
    Column("authority_refs", JSONB, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

routing_insight_candidates = Table(
    "routing_insight_candidates",
    metadata,
    Column("insight_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("source_kind", Text, nullable=False),
    Column("source_ref", Text, nullable=False),
    Column("proposal", JSONB, nullable=False),
    Column("evidence_refs", JSONB, nullable=False),
    Column("confidence", Numeric, nullable=False),
    Column("state", Text, nullable=False),
    Column("evaluation_refs", JSONB, nullable=False),
    Column("promoted_policy_ref", Text, nullable=True),
    Column("promoted_by", Uuid(as_uuid=True), nullable=True),
    Column("promoted_at", TIMESTAMP(timezone=True), nullable=True),
    Column("lock_version", Integer, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)
