-- GENERATED from schemas/objects. Do not edit.

DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS command_idempotency CASCADE;
DROP TABLE IF EXISTS outbox CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS evidence CASCADE;
DROP TABLE IF EXISTS verification_runs CASCADE;
DROP TABLE IF EXISTS artifacts CASCADE;
DROP TABLE IF EXISTS worker_events CASCADE;
DROP TABLE IF EXISTS worker_runs CASCADE;
DROP TABLE IF EXISTS task_attempts CASCADE;
DROP TABLE IF EXISTS execution_plans CASCADE;
DROP TABLE IF EXISTS workspaces CASCADE;
DROP TABLE IF EXISTS execution_environments CASCADE;
DROP TABLE IF EXISTS route_decisions CASCADE;
DROP TABLE IF EXISTS context_packages CASCADE;
DROP TABLE IF EXISTS task_graph_edges CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS task_graphs CASCADE;
DROP TABLE IF EXISTS missions CASCADE;
DROP TABLE IF EXISTS edrs CASCADE;
DROP TABLE IF EXISTS requirements CASCADE;
DROP TABLE IF EXISTS product_constitution_versions CASCADE;
DROP TABLE IF EXISTS principal_grants CASCADE;
DROP TABLE IF EXISTS principals CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
