"""SQLAlchemy mirrors of the schema-generated Production VEKL tables."""

from __future__ import annotations

from sqlalchemy import TIMESTAMP, Column, Integer, MetaData, Table, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

projects = Table(
    "projects",
    metadata,
    Column("project_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("slug", Text, nullable=False),
    Column("kind", Text),
)

vekl_resources = Table(
    "vekl_resources",
    metadata,
    Column("resource_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("parent_resource_id", Uuid(as_uuid=True)),
    Column("source_id", Uuid(as_uuid=True)),
    Column("source_artifact_id", Uuid(as_uuid=True)),
    Column("resource_kind", Text, nullable=False),
    Column("component_kind", Text),
    Column("title", Text, nullable=False),
    Column("publisher", Text, nullable=False),
    Column("source_uri", Text),
    Column("revision", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("source_trust", Text, nullable=False),
    Column("reuse_class", Text, nullable=False),
    Column("lifecycle_state", Text, nullable=False),
    Column("activation_modes", JSONB, nullable=False),
    Column("exact_versions", JSONB, nullable=False),
    Column("license_ids", JSONB, nullable=False),
    Column("provenance", JSONB, nullable=False),
    Column("required_capabilities", JSONB, nullable=False),
    Column("filesystem_scopes", JSONB, nullable=False),
    Column("network_scopes", JSONB, nullable=False),
    Column("secret_scopes", JSONB, nullable=False),
    Column("sandbox_requirements", JSONB, nullable=False),
    Column("side_effect_class", Text, nullable=False),
    Column("required_verifiers", JSONB, nullable=False),
    Column("stack_constraints", JSONB, nullable=False),
    Column("truth_constraints", JSONB, nullable=False),
    Column("freshness", JSONB, nullable=False),
    Column("budget", JSONB, nullable=False),
    Column("injection_findings", JSONB, nullable=False),
    Column("content_excerpt", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

stack_fingerprints = Table(
    "stack_fingerprints",
    metadata,
    Column("fingerprint_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("facts", JSONB, nullable=False),
    Column("evidence_refs", JSONB, nullable=False),
    Column("fingerprint_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

task_signatures = Table(
    "task_signatures",
    metadata,
    Column("signature_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("task_id", Uuid(as_uuid=True), nullable=False),
    Column("fingerprint_id", Uuid(as_uuid=True), nullable=False),
    Column("lifecycle_stage", Text, nullable=False),
    Column("task_class", Text, nullable=False),
    Column("constraints", JSONB, nullable=False),
    Column("risk_category", Text, nullable=False),
    Column("error_signatures", JSONB),
    Column("required_capabilities", JSONB, nullable=False),
    Column("allowed_filesystem_scopes", JSONB),
    Column("allowed_network_scopes", JSONB),
    Column("allowed_secret_scopes", JSONB),
    Column("required_verifiers", JSONB, nullable=False),
    Column("freshness_needs", JSONB, nullable=False),
    Column("budget", JSONB, nullable=False),
    Column("signature_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_activation_manifests = Table(
    "vekl_activation_manifests",
    metadata,
    Column("manifest_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True)),
    Column("task_id", Uuid(as_uuid=True), nullable=False),
    Column("task_attempt_id", Uuid(as_uuid=True)),
    Column("worker_run_id", Uuid(as_uuid=True)),
    Column("task_signature_id", Uuid(as_uuid=True), nullable=False),
    Column("stack_fingerprint_id", Uuid(as_uuid=True), nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("stack_fingerprint_hash", Text, nullable=False),
    Column("policy_hash", Text, nullable=False),
    Column("selected_resources", JSONB, nullable=False),
    Column("tools", JSONB, nullable=False),
    Column("hooks", JSONB, nullable=False),
    Column("loops", JSONB, nullable=False),
    Column("community_evidence", JSONB, nullable=False),
    Column("freshness_state", JSONB, nullable=False),
    Column("manifest_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_manifest_invalidations = Table(
    "vekl_manifest_invalidations",
    metadata,
    Column("invalidation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("manifest_id", Uuid(as_uuid=True), nullable=False),
    Column("reason_code", Text, nullable=False),
    Column("detail", JSONB, nullable=False),
    Column("observed_policy_hash", Text, nullable=False),
    Column("observed_truth_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_resource_outcomes = Table(
    "vekl_resource_outcomes",
    metadata,
    Column("outcome_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("manifest_id", Uuid(as_uuid=True), nullable=False),
    Column("resource_revisions", JSONB, nullable=False),
    Column("verifier_refs", JSONB, nullable=False),
    Column("verified_outcome", Text, nullable=False),
    Column("regressions", JSONB, nullable=False),
    Column("iterations", Integer, nullable=False),
    Column("rework", JSONB, nullable=False),
    Column("cost", JSONB, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("failure_signatures", JSONB, nullable=False),
    Column("evidence_refs", JSONB, nullable=False),
    Column("recorded_by", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)
