"""SQLAlchemy mirrors of the schema-generated Production VEKL tables."""

from __future__ import annotations

from sqlalchemy import TIMESTAMP, Boolean, Column, Integer, MetaData, Table, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()

projects = Table(
    "projects",
    metadata,
    Column("project_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("slug", Text, nullable=False),
    Column("kind", Text),
)

vekl_resources = Table(
    "vekl_resources",
    metadata,
    Column("resource_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("parent_resource_id", Uuid(as_uuid=True)),
    Column("source_id", Uuid(as_uuid=True)),
    Column("source_artifact_id", Uuid(as_uuid=True)),
    Column("resource_kind", Text, nullable=False),
    Column("component_kind", Text),
    Column("title", Text, nullable=False),
    Column("publisher", Text, nullable=False),
    Column("source_uri", Text),
    Column("revision", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("source_trust", Text, nullable=False),
    Column("reuse_class", Text, nullable=False),
    Column("lifecycle_state", Text, nullable=False),
    Column("activation_modes", JSONB, nullable=False),
    Column("exact_versions", JSONB, nullable=False),
    Column("license_ids", JSONB, nullable=False),
    Column("provenance", JSONB, nullable=False),
    Column("required_capabilities", JSONB, nullable=False),
    Column("filesystem_scopes", JSONB, nullable=False),
    Column("network_scopes", JSONB, nullable=False),
    Column("secret_scopes", JSONB, nullable=False),
    Column("sandbox_requirements", JSONB, nullable=False),
    Column("side_effect_class", Text, nullable=False),
    Column("required_verifiers", JSONB, nullable=False),
    Column("stack_constraints", JSONB, nullable=False),
    Column("truth_constraints", JSONB, nullable=False),
    Column("freshness", JSONB, nullable=False),
    Column("budget", JSONB, nullable=False),
    Column("injection_findings", JSONB, nullable=False),
    Column("content_excerpt", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

stack_fingerprints = Table(
    "stack_fingerprints",
    metadata,
    Column("fingerprint_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("facts", JSONB, nullable=False),
    Column("evidence_refs", JSONB, nullable=False),
    Column("fingerprint_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

task_signatures = Table(
    "task_signatures",
    metadata,
    Column("signature_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("task_id", Uuid(as_uuid=True), nullable=False),
    Column("fingerprint_id", Uuid(as_uuid=True), nullable=False),
    Column("lifecycle_stage", Text, nullable=False),
    Column("task_class", Text, nullable=False),
    Column("constraints", JSONB, nullable=False),
    Column("risk_category", Text, nullable=False),
    Column("error_signatures", JSONB),
    Column("required_capabilities", JSONB, nullable=False),
    Column("allowed_filesystem_scopes", JSONB),
    Column("allowed_network_scopes", JSONB),
    Column("allowed_secret_scopes", JSONB),
    Column("required_verifiers", JSONB, nullable=False),
    Column("freshness_needs", JSONB, nullable=False),
    Column("budget", JSONB, nullable=False),
    Column("signature_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_activation_manifests = Table(
    "vekl_activation_manifests",
    metadata,
    Column("manifest_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True)),
    Column("task_id", Uuid(as_uuid=True), nullable=False),
    Column("task_attempt_id", Uuid(as_uuid=True)),
    Column("worker_run_id", Uuid(as_uuid=True)),
    Column("task_signature_id", Uuid(as_uuid=True), nullable=False),
    Column("stack_fingerprint_id", Uuid(as_uuid=True), nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("stack_fingerprint_hash", Text, nullable=False),
    Column("policy_hash", Text, nullable=False),
    Column("knowledge_context", JSONB, nullable=False),
    Column("selected_resources", JSONB, nullable=False),
    Column("tools", JSONB, nullable=False),
    Column("hooks", JSONB, nullable=False),
    Column("loops", JSONB, nullable=False),
    Column("community_evidence", JSONB, nullable=False),
    Column("freshness_state", JSONB, nullable=False),
    Column("manifest_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_manifest_invalidations = Table(
    "vekl_manifest_invalidations",
    metadata,
    Column("invalidation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("manifest_id", Uuid(as_uuid=True), nullable=False),
    Column("reason_code", Text, nullable=False),
    Column("detail", JSONB, nullable=False),
    Column("observed_policy_hash", Text, nullable=False),
    Column("observed_truth_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_resource_outcomes = Table(
    "vekl_resource_outcomes",
    metadata,
    Column("outcome_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("manifest_id", Uuid(as_uuid=True), nullable=False),
    Column("resource_revisions", JSONB, nullable=False),
    Column("verifier_refs", JSONB, nullable=False),
    Column("verified_outcome", Text, nullable=False),
    Column("regressions", JSONB, nullable=False),
    Column("iterations", Integer, nullable=False),
    Column("rework", JSONB, nullable=False),
    Column("cost", JSONB, nullable=False),
    Column("latency_ms", Integer, nullable=False),
    Column("failure_signatures", JSONB, nullable=False),
    Column("evidence_refs", JSONB, nullable=False),
    Column("recorded_by", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)


vekl_unit_maps = Table(
    "vekl_unit_maps",
    metadata,
    Column("unit_map_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=False),
    Column("task_graph_id", Uuid(as_uuid=True), nullable=False),
    Column("task_graph_version", Integer, nullable=False),
    Column("task_ids", JSONB, nullable=False),
    Column("unit_lineage_id", Text, nullable=False),
    Column("unit_revision_hash", Text, nullable=False),
    Column("unit_boundary_policy_version", Text, nullable=False),
    Column("unit_projection_compiler_version", Text, nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("applicable_truth_slice_hash", Text, nullable=False),
    Column("stack_fingerprint_id", Uuid(as_uuid=True), nullable=False),
    Column("stack_fingerprint_hash", Text, nullable=False),
    Column("contract_set_hash", Text, nullable=False),
    Column("product_experience_hash", Text),
    Column("retrieval_route_policy_hash", Text, nullable=False),
    Column("objective", Text, nullable=False),
    Column("scope", JSONB, nullable=False),
    Column("requirement_refs", JSONB, nullable=False),
    Column("edr_refs", JSONB, nullable=False),
    Column("constitution_refs", JSONB, nullable=False),
    Column("upstream_task_refs", JSONB, nullable=False),
    Column("downstream_task_refs", JSONB, nullable=False),
    Column("contracts_consumed", JSONB, nullable=False),
    Column("contracts_produced", JSONB, nullable=False),
    Column("code_targets", JSONB, nullable=False),
    Column("workspace_refs", JSONB, nullable=False),
    Column("product_experience_refs", JSONB, nullable=False),
    Column("security_refs", JSONB, nullable=False),
    Column("eventuality_refs", JSONB, nullable=False),
    Column("research_questions", JSONB, nullable=False),
    Column("knowledge_route_ids", JSONB, nullable=False),
    Column("required_verifiers", JSONB, nullable=False),
    Column("knowledge_readiness_state", Text, nullable=False),
    Column("knowledge_exemption", JSONB),
    Column("challenge_state", Text, nullable=False),
    Column("unit_map_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    Column("invalidated_at", TIMESTAMP(timezone=True)),
    Column("invalidation_reasons", JSONB, nullable=False),
)

vekl_knowledge_nodes = Table(
    "vekl_knowledge_nodes",
    metadata,
    Column("knowledge_node_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("node_kind", Text, nullable=False),
    Column("object_type", Text, nullable=False),
    Column("object_id", Uuid(as_uuid=True)),
    Column("stable_ref", Text, nullable=False),
    Column("authority_class", Text, nullable=False),
    Column("authority_service", Text, nullable=False),
    Column("source_revision", Text),
    Column("content_hash", Text, nullable=False),
    Column("projection_compiler_version", Text, nullable=False),
    Column("project_truth_hash", Text),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    Column("invalidated_at", TIMESTAMP(timezone=True)),
)

vekl_knowledge_edges = Table(
    "vekl_knowledge_edges",
    metadata,
    Column("knowledge_edge_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("from_node_id", Uuid(as_uuid=True), nullable=False),
    Column("relationship", Text, nullable=False),
    Column("to_node_id", Uuid(as_uuid=True), nullable=False),
    Column("provenance_ref", Text, nullable=False),
    Column("provenance_hash", Text, nullable=False),
    Column("derivation_class", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    Column("invalidated_at", TIMESTAMP(timezone=True)),
)

vekl_retrieval_routes = Table(
    "vekl_retrieval_routes",
    metadata,
    Column("route_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("route_slug", Text, nullable=False),
    Column("version", Text, nullable=False),
    Column("concern", Text, nullable=False),
    Column("policy", JSONB, nullable=False),
    Column("policy_hash", Text, nullable=False),
    Column("active", Boolean, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_research_findings = Table(
    "vekl_research_findings",
    metadata,
    Column("finding_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("unit_map_id", Uuid(as_uuid=True), nullable=False),
    Column("task_refs", JSONB, nullable=False),
    Column("concern", Text, nullable=False),
    Column("source_id", Uuid(as_uuid=True)),
    Column("source_artifact_id", Uuid(as_uuid=True)),
    Column("resource_id", Uuid(as_uuid=True)),
    Column("source_trust", Text, nullable=False),
    Column("source_revision", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("claim", Text, nullable=False),
    Column("supporting_excerpt_hash", Text, nullable=False),
    Column("freshness", JSONB, nullable=False),
    Column("classification", Text, nullable=False),
    Column("confidence", Text, nullable=False),
    Column("corroboration_refs", JSONB, nullable=False),
    Column("project_truth_refs", JSONB, nullable=False),
    Column("stack_refs", JSONB, nullable=False),
    Column("impact_hypothesis", JSONB, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_conflict_observations = Table(
    "vekl_conflict_observations",
    metadata,
    Column("observation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("resource_id", Uuid(as_uuid=True), nullable=False),
    Column("finding_id", Uuid(as_uuid=True), nullable=False),
    Column("current_truth_hash", Text, nullable=False),
    Column("conflicting_truth_refs", JSONB, nullable=False),
    Column("conflict_keys", JSONB, nullable=False),
    Column("source_trust", Text, nullable=False),
    Column("freshness", JSONB, nullable=False),
    Column("provenance_valid", Boolean, nullable=False),
    Column("activation_rejected", Boolean, nullable=False),
    Column("challenge_evaluation_requested", Boolean, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_truth_challenges = Table(
    "vekl_truth_challenges",
    metadata,
    Column("challenge_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=False),
    Column("task_id", Uuid(as_uuid=True)),
    Column("challenge_class", Text, nullable=False),
    Column("severity", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("current_truth_hash", Text, nullable=False),
    Column("evidence", JSONB, nullable=False),
    Column("conflict", JSONB, nullable=False),
    Column("confidence", JSONB, nullable=False),
    Column("impact", JSONB, nullable=False),
    Column("proposal", JSONB, nullable=False),
    Column("decision_analysis", JSONB, nullable=False),
    Column("approval_id", Uuid(as_uuid=True)),
    Column("required_role", Text, nullable=False),
    Column("decision", Text),
    Column("decision_reason", Text),
    Column("decided_at", TIMESTAMP(timezone=True)),
    Column("reopen_conditions", JSONB, nullable=False),
    Column("challenge_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_truth_challenge_findings = Table(
    "vekl_truth_challenge_findings",
    metadata,
    Column("challenge_finding_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("challenge_id", Uuid(as_uuid=True), nullable=False),
    Column("finding_id", Uuid(as_uuid=True), nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_graph_invalidations = Table(
    "vekl_graph_invalidations",
    metadata,
    Column("graph_invalidation_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("unit_map_id", Uuid(as_uuid=True)),
    Column("manifest_id", Uuid(as_uuid=True)),
    Column("resolution_trace_id", Uuid(as_uuid=True)),
    Column("reason_code", Text, nullable=False),
    Column("detail", JSONB, nullable=False),
    Column("observed_truth_hash", Text, nullable=False),
    Column("previous_hash", Text),
    Column("observed_hash", Text),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_resolution_traces = Table(
    "vekl_resolution_traces",
    metadata,
    Column("resolution_trace_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("mission_id", Uuid(as_uuid=True), nullable=False),
    Column("task_graph_id", Uuid(as_uuid=True), nullable=False),
    Column("task_ids", JSONB, nullable=False),
    Column("unit_map_id", Uuid(as_uuid=True), nullable=False),
    Column("unit_lineage_id", Text, nullable=False),
    Column("unit_revision_hash", Text, nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("applicable_truth_slice_hash", Text, nullable=False),
    Column("stack_fingerprint_hash", Text, nullable=False),
    Column("task_signature_hash", Text, nullable=False),
    Column("contract_set_hash", Text, nullable=False),
    Column("graph_snapshot_hash", Text, nullable=False),
    Column("resolution_envelope", JSONB, nullable=False),
    Column("traversed_node_ids", JSONB, nullable=False),
    Column("traversed_edge_ids", JSONB, nullable=False),
    Column("candidate_decisions", JSONB, nullable=False),
    Column("withheld_truth_conflicts", JSONB, nullable=False),
    Column("challenge_observation_refs", JSONB, nullable=False),
    Column("trace_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
)

vekl_execution_knowledge_bindings = Table(
    "vekl_execution_knowledge_bindings",
    metadata,
    Column("execution_binding_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("resolution_trace_id", Uuid(as_uuid=True), nullable=False),
    Column("binding_stage", Text, nullable=False),
    Column("project_truth_hash", Text, nullable=False),
    Column("unit_lineage_id", Text, nullable=False),
    Column("unit_revision_hash", Text, nullable=False),
    Column("graph_revision_hash", Text, nullable=False),
    Column("graph_neighbourhood_hash", Text, nullable=False),
    Column("applicable_contract_fingerprints", JSONB, nullable=False),
    Column("technical_stack_fingerprint", Text, nullable=False),
    Column("knowledge_route_policy_hash", Text, nullable=False),
    Column("determinism_envelope_hash", Text, nullable=False),
    Column("activation_manifest_id", Uuid(as_uuid=True), nullable=False),
    Column("activation_manifest_hash", Text, nullable=False),
    Column("context_package_id", Uuid(as_uuid=True)),
    Column("context_package_hash", Text),
    Column("context_capsule_hashes", JSONB, nullable=False),
    Column("worker_delivery_hash", Text, nullable=False),
    Column("binding_hash", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
)
