# ruff: noqa: E501
"""EDR-0019 cross-system operational intelligence and execution hardening.

Phase 2 persistence for the DDE-native contracts accepted by EDR-0019. Every statement
below is the generated DDL from schemas/objects (schemas/sql/0001_stage1.sql); the
migration never diverges from the schema authority by hand.

Revision ID: 0041
Revises: 0040
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0041"
down_revision = "0040"
branch_labels = None
depends_on = None


_CREATE_TABLES = (
    """CREATE TABLE discovery_candidates (
    candidate_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    canonical_locator text NOT NULL,
    normalized_identity_key text NOT NULL,
    identity_scheme text NOT NULL,
    title text,
    publisher text,
    lifecycle_state text NOT NULL,
    source_trust text NOT NULL,
    discovered_by text NOT NULL,
    discovery_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    observation_count integer NOT NULL,
    source_id uuid,
    admitted_resource_id uuid,
    supersedes_candidate_id uuid,
    license_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    content_hash text,
    sanitizer_findings jsonb NOT NULL DEFAULT '[]'::jsonb,
    architecture_findings jsonb NOT NULL DEFAULT '[]'::jsonb,
    first_seen_at timestamptz NOT NULL,
    last_observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (candidate_id),
    UNIQUE (tenant_id, project_id, normalized_identity_key)
);""",
    """CREATE TABLE discovery_transitions (
    transition_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    sequence integer NOT NULL,
    from_state text,
    to_state text NOT NULL,
    reason_code text NOT NULL,
    actor text NOT NULL,
    evidence_pointer text,
    decision_hash text NOT NULL,
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (transition_id),
    UNIQUE (candidate_id, sequence)
);""",
    """CREATE TABLE discovery_observations (
    observation_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    observed_via text NOT NULL,
    observer_ref text,
    claim_excerpt_hash text,
    content_hash text,
    corroborates_observation_id uuid,
    observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (observation_id)
);""",
    """CREATE TABLE discovery_trials (
    trial_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    trial_kind text NOT NULL,
    sandbox_profile text NOT NULL,
    declared_network_scopes jsonb NOT NULL DEFAULT '[]'::jsonb,
    declared_filesystem_scopes jsonb NOT NULL DEFAULT '[]'::jsonb,
    capability_lease_id uuid,
    command jsonb NOT NULL DEFAULT '[]'::jsonb,
    input_digest text,
    outcome text NOT NULL,
    observed_signals jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_pointer text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (trial_id)
);""",
    """CREATE TABLE discovery_qualifications (
    qualification_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    disposition text NOT NULL,
    authority_ceiling text NOT NULL,
    allowed_uses jsonb NOT NULL DEFAULT '[]'::jsonb,
    forbidden_uses jsonb NOT NULL DEFAULT '[]'::jsonb,
    guidance_polarity text NOT NULL,
    rationale text NOT NULL,
    policy_revision text NOT NULL,
    trial_id uuid,
    admission_id uuid,
    resource_id uuid,
    hold_expires_at timestamptz,
    qualified_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (qualification_id)
);""",
    """CREATE TABLE research_missions (
    research_mission_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid,
    unit_map_id uuid,
    title text NOT NULL,
    required_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
    optional_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
    target_unit_revisions jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL,
    mission_definition_hash text NOT NULL,
    coverage_hash text,
    policy_revision text NOT NULL,
    budget jsonb NOT NULL DEFAULT '{}'::jsonb,
    egress_profile text NOT NULL,
    cells_total integer NOT NULL,
    cells_complete integer NOT NULL,
    cells_conflicted integer NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (research_mission_id)
);""",
    """CREATE TABLE research_cells (
    cell_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    research_mission_id uuid NOT NULL,
    unit_revision text NOT NULL,
    dimension text NOT NULL,
    state text NOT NULL,
    attempts integer NOT NULL,
    retry_count integer NOT NULL,
    last_error_class text,
    stale_reason text,
    stale_invalidated_at timestamptz,
    first_pass_at timestamptz,
    deep_evidence_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (cell_id),
    UNIQUE (research_mission_id, unit_revision, dimension)
);""",
    """CREATE TABLE research_packets (
    packet_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    research_mission_id uuid NOT NULL,
    unit_revision text NOT NULL,
    revision integer NOT NULL,
    state text NOT NULL,
    required_dimensions_covered jsonb NOT NULL DEFAULT '[]'::jsonb,
    missing_dimensions jsonb NOT NULL DEFAULT '[]'::jsonb,
    finding_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    conflict_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    freshness jsonb NOT NULL DEFAULT '{}'::jsonb,
    relevance jsonb NOT NULL DEFAULT '{}'::jsonb,
    graph_compiled boolean NOT NULL,
    capsule_compiled boolean NOT NULL,
    activation_eligible boolean NOT NULL,
    activation_block_reason text,
    regressed_from_revision integer,
    completeness_hash text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (packet_id),
    UNIQUE (research_mission_id, unit_revision, revision)
);""",
    """CREATE TABLE research_provider_runs (
    provider_run_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    research_mission_id uuid NOT NULL,
    cell_id uuid,
    stage text NOT NULL,
    provider_id text NOT NULL,
    model_identity_requested text,
    model_identity_attested text,
    request_class text NOT NULL,
    sanitized_query_hash text NOT NULL,
    egress_recorded boolean NOT NULL,
    returned_evidence_hashes jsonb NOT NULL DEFAULT '[]'::jsonb,
    admitted_source_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    outcome text NOT NULL,
    error_class text,
    cost jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (provider_run_id)
);""",
    """CREATE TABLE research_conflicts (
    conflict_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    research_mission_id uuid NOT NULL,
    unit_revision text NOT NULL,
    dimension text NOT NULL,
    conflict_class text NOT NULL,
    finding_a_ref text NOT NULL,
    finding_b_ref text,
    project_truth_ref text,
    status text NOT NULL,
    truth_challenge_id uuid,
    resolution_note text,
    detected_at timestamptz NOT NULL,
    resolved_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (conflict_id)
);""",
    """CREATE TABLE research_cursors (
    cursor_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    research_mission_id uuid NOT NULL,
    coverage_revision integer NOT NULL,
    packet_revision integer NOT NULL,
    admission_revision integer NOT NULL,
    graph_revision integer NOT NULL,
    last_event_sequence integer NOT NULL,
    last_cell_id uuid,
    last_packet_id uuid,
    last_provider_run_id uuid,
    observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (cursor_id)
);""",
    """CREATE TABLE provider_readiness_snapshots (
    readiness_snapshot_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    provider_id text NOT NULL,
    harness_id text,
    endpoint_id uuid,
    environment text NOT NULL,
    readiness_state text NOT NULL,
    capacity_snapshot_id uuid,
    model_identity_expected text,
    model_identity_attested text,
    identity_drift boolean NOT NULL,
    qualification_evidence_pointer text,
    evidence_recorded_at timestamptz,
    evidence_expires_at timestamptz,
    evidence_fresh boolean NOT NULL,
    probe_method text,
    last_probe_at timestamptz,
    degraded_code text,
    blocking_scope text,
    owner_action_required boolean NOT NULL,
    observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (readiness_snapshot_id),
    CHECK ((readiness_state <> 'READY') OR (evidence_fresh AND qualification_evidence_pointer IS NOT NULL))
);""",
    """CREATE TABLE execution_placement_decisions (
    placement_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid,
    task_id uuid,
    task_execution_descriptor_ref text,
    required_capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
    candidate_providers jsonb NOT NULL DEFAULT '[]'::jsonb,
    excluded_providers jsonb NOT NULL DEFAULT '[]'::jsonb,
    selected_provider text NOT NULL,
    selected_harness text,
    model_identity_requested text,
    model_identity_attested text,
    capacity_snapshot_id uuid,
    readiness_snapshot_id uuid,
    fallback_chain jsonb NOT NULL DEFAULT '[]'::jsonb,
    fallback_checkpoint_kind text,
    fallback_of_placement_id uuid,
    carried_work_state_hash text,
    carried_diff_hash text,
    carried_context_hash text,
    decision_hash text NOT NULL,
    decided_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (placement_id)
);""",
    """CREATE TABLE capability_gates (
    gate_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    capability_id text NOT NULL,
    provider_id text,
    environment text NOT NULL,
    desired_state text NOT NULL,
    configuration_state text NOT NULL,
    reachability_state text NOT NULL,
    qualification_state text NOT NULL,
    readiness_state text NOT NULL,
    degraded_code text,
    degraded_contract jsonb,
    evidence_pointer text,
    last_probe_at timestamptz,
    expires_at timestamptz,
    blocking_scope text NOT NULL,
    owner_action_required boolean NOT NULL,
    owner_action_note text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (gate_id),
    UNIQUE (tenant_id, project_id, capability_id, environment),
    CHECK ((readiness_state <> 'READY') OR (evidence_pointer IS NOT NULL AND last_probe_at IS NOT NULL))
);""",
    """CREATE TABLE capability_gate_probes (
    probe_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    gate_id uuid NOT NULL,
    probe_kind text NOT NULL,
    outcome text NOT NULL,
    observed_identity text,
    expected_identity text,
    latency_ms integer,
    detail_hash text,
    evidence_pointer text,
    observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (probe_id)
);""",
    """CREATE TABLE environment_certifications (
    certification_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    environment text NOT NULL,
    environment_id uuid,
    capability_id text NOT NULL,
    desired boolean NOT NULL,
    configured boolean NOT NULL,
    live boolean NOT NULL,
    qualified boolean NOT NULL,
    evidenced boolean NOT NULL,
    evidence_fresh boolean NOT NULL,
    green boolean NOT NULL,
    self_test_classes jsonb NOT NULL DEFAULT '[]'::jsonb,
    self_test_results jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_pointer text,
    certified_at timestamptz,
    expires_at timestamptz,
    certification_hash text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (certification_id),
    UNIQUE (tenant_id, project_id, environment, capability_id),
    CHECK ((NOT green) OR (desired AND configured AND live AND qualified AND evidenced AND evidence_fresh))
);""",
    """CREATE TABLE mission_steer_requests (
    steer_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid NOT NULL,
    requested_by_principal_id uuid,
    authority_class text NOT NULL,
    read_only boolean NOT NULL,
    material boolean NOT NULL,
    intent_text_hash text NOT NULL,
    intent_summary text NOT NULL,
    state text NOT NULL,
    disposition text,
    requires_truth_change boolean NOT NULL,
    truth_change_ref text,
    supersedes_steer_id uuid,
    barrier_id uuid,
    acknowledged_at timestamptz,
    safe_boundary_at timestamptz,
    applied_at timestamptz,
    evidence_pointer text,
    decision_hash text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (steer_id),
    CHECK ((NOT read_only) OR (barrier_id IS NULL)),
    CHECK ((authority_class <> 'NO_AUTHORITY') OR read_only)
);""",
    """CREATE TABLE steering_barriers (
    barrier_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    steer_id uuid NOT NULL,
    mission_id uuid NOT NULL,
    scope_kind text NOT NULL,
    write_ownership_scope jsonb NOT NULL DEFAULT '[]'::jsonb,
    blocked_lease_kinds jsonb NOT NULL DEFAULT '[]'::jsonb,
    state text NOT NULL,
    active_writer_count integer NOT NULL,
    awaited_writer_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    opened_at timestamptz NOT NULL,
    drained_at timestamptz,
    released_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (barrier_id)
);""",
    """CREATE TABLE safe_boundary_receipts (
    receipt_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    barrier_id uuid NOT NULL,
    steer_id uuid NOT NULL,
    writer_ref text NOT NULL,
    worker_run_id uuid,
    task_id uuid,
    boundary_kind text NOT NULL,
    change_packet_ref text,
    change_packet_disposition text,
    workspace_revision text,
    evidence_pointer text,
    reached_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (receipt_id)
);""",
    """CREATE TABLE steering_impacts (
    impact_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    steer_id uuid NOT NULL,
    task_id uuid NOT NULL,
    impact_kind text NOT NULL,
    hold_state text NOT NULL,
    previous_task_status text,
    closed_lease_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    reason_code text NOT NULL,
    held_at timestamptz,
    released_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (impact_id),
    UNIQUE (steer_id, task_id)
);""",
    """CREATE TABLE context_facts (
    fact_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    subject text NOT NULL,
    predicate text NOT NULL,
    value jsonb NOT NULL DEFAULT '{}'::jsonb,
    authority_class text NOT NULL,
    source_trust text,
    source_ref text,
    valid_from timestamptz NOT NULL,
    valid_until timestamptz,
    observed_at timestamptz NOT NULL,
    superseded_by_fact_id uuid,
    supersession_reason text,
    promoted_from_authority_class text,
    promoted_by_ref text,
    content_hash text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (fact_id),
    CHECK ((authority_class <> 'MODEL_INFERENCE') OR (promoted_by_ref IS NULL))
);""",
    """CREATE TABLE attention_candidates (
    candidate_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid,
    attention_class text NOT NULL,
    dedupe_key text NOT NULL,
    summary text NOT NULL,
    source_event_ref text,
    importance numeric NOT NULL,
    urgency numeric NOT NULL,
    actionability numeric NOT NULL,
    novelty numeric NOT NULL,
    confidence numeric NOT NULL,
    blast_radius numeric NOT NULL,
    time_sensitivity numeric NOT NULL,
    owner_required boolean NOT NULL,
    repeat_penalty numeric NOT NULL,
    score numeric NOT NULL,
    repeat_count integer NOT NULL,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    disposition text NOT NULL,
    bypassed_budget boolean NOT NULL,
    attention_id uuid,
    snoozed_until timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (candidate_id),
    UNIQUE (tenant_id, project_id, dedupe_key),
    CHECK ((NOT bypassed_budget) OR attention_class IN ('SECURITY','APPROVAL','URGENT'))
);""",
    """CREATE TABLE attention_preferences (
    preference_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    max_nonurgent_per_hour integer NOT NULL,
    max_nonurgent_per_day integer NOT NULL,
    quiet_hours jsonb NOT NULL DEFAULT '[]'::jsonb,
    timezone text NOT NULL,
    repeat_cooldown_seconds integer NOT NULL,
    escalation_after_seconds integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (preference_id),
    UNIQUE (tenant_id, project_id)
);""",
    """CREATE TABLE automation_workflow_definitions (
    definition_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    runtime_kind text NOT NULL,
    name text NOT NULL,
    intent_summary text NOT NULL,
    authored_by text NOT NULL,
    derived_from_descriptor_id uuid,
    definition_hash text NOT NULL,
    node_inventory jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (definition_id)
);""",
    """CREATE TABLE automation_workflow_releases (
    release_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    definition_id uuid NOT NULL,
    version text NOT NULL,
    release_hash text NOT NULL,
    lifecycle_state text NOT NULL,
    node_policy_findings jsonb NOT NULL DEFAULT '[]'::jsonb,
    prohibited_nodes_present jsonb NOT NULL DEFAULT '[]'::jsonb,
    gated_nodes_present jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_external_domains jsonb NOT NULL DEFAULT '[]'::jsonb,
    action_class_ceiling text NOT NULL,
    security_evidence_pointer text,
    sandbox_evidence_pointer text,
    revoked_reason text,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (release_id),
    UNIQUE (definition_id, version),
    CHECK ((lifecycle_state <> 'PRODUCTION_QUALIFIED') OR (security_evidence_pointer IS NOT NULL AND sandbox_evidence_pointer IS NOT NULL))
);""",
    """CREATE TABLE automation_run_grants (
    grant_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    run_id uuid NOT NULL,
    release_id uuid NOT NULL,
    capability_id text NOT NULL,
    task_execution_descriptor_ref text,
    context_hash text NOT NULL,
    input_digest text NOT NULL,
    allowed_gateway_operations jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_external_domains jsonb NOT NULL DEFAULT '[]'::jsonb,
    action_class_ceiling text NOT NULL,
    max_uses integer NOT NULL,
    uses_consumed integer NOT NULL,
    nonce text NOT NULL,
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    state text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (grant_id),
    UNIQUE (tenant_id, project_id, nonce),
    CHECK (uses_consumed <= max_uses)
);""",
    """CREATE TABLE automation_runs (
    run_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid,
    task_id uuid,
    release_id uuid NOT NULL,
    capability_lease_id uuid,
    runtime_execution_ref text,
    state text NOT NULL,
    callback_grant_valid boolean,
    effect_journal_consistent boolean,
    external_effect_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    verification_ref text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (run_id),
    CHECK ((state <> 'VERIFIED') OR (callback_grant_valid AND effect_journal_consistent AND verification_ref IS NOT NULL))
);""",
    """CREATE TABLE browser_capability_sessions (
    session_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    mission_id uuid,
    task_id uuid,
    capability_level text NOT NULL,
    profile_ref text NOT NULL,
    profile_isolated boolean NOT NULL,
    capability_lease_id uuid,
    allowed_domains jsonb NOT NULL DEFAULT '[]'::jsonb,
    semantic_layer_used boolean NOT NULL,
    verification_authority text NOT NULL,
    screenshot_redaction boolean NOT NULL,
    cookie_export_blocked boolean NOT NULL,
    state text NOT NULL,
    refusal_reason text,
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    closed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (session_id),
    CHECK (profile_isolated),
    CHECK (cookie_export_blocked)
);""",
    """CREATE TABLE external_effect_verifications (
    verification_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    project_id uuid NOT NULL,
    effect_id uuid NOT NULL,
    verifier_type text NOT NULL,
    independent_of_adapter boolean NOT NULL,
    observed_postcondition text NOT NULL,
    outcome text NOT NULL,
    correlation text,
    evidence_pointer text,
    observation_hash text NOT NULL,
    observed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (verification_id)
);""",
)

_FOREIGN_KEYS = (
    """ALTER TABLE discovery_candidates ADD CONSTRAINT discovery_candidates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE discovery_candidates ADD CONSTRAINT discovery_candidates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE discovery_candidates ADD CONSTRAINT discovery_candidates_source_id_fkey FOREIGN KEY (source_id) REFERENCES source_records (source_id);""",
    """ALTER TABLE discovery_candidates ADD CONSTRAINT discovery_candidates_resource_id_fkey FOREIGN KEY (admitted_resource_id) REFERENCES vekl_resources (resource_id);""",
    """ALTER TABLE discovery_transitions ADD CONSTRAINT discovery_transitions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE discovery_transitions ADD CONSTRAINT discovery_transitions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE discovery_transitions ADD CONSTRAINT discovery_transitions_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES discovery_candidates (candidate_id);""",
    """ALTER TABLE discovery_observations ADD CONSTRAINT discovery_observations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE discovery_observations ADD CONSTRAINT discovery_observations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE discovery_observations ADD CONSTRAINT discovery_observations_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES discovery_candidates (candidate_id);""",
    """ALTER TABLE discovery_trials ADD CONSTRAINT discovery_trials_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE discovery_trials ADD CONSTRAINT discovery_trials_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE discovery_trials ADD CONSTRAINT discovery_trials_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES discovery_candidates (candidate_id);""",
    """ALTER TABLE discovery_trials ADD CONSTRAINT discovery_trials_lease_id_fkey FOREIGN KEY (capability_lease_id) REFERENCES capability_leases (lease_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES discovery_candidates (candidate_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_trial_id_fkey FOREIGN KEY (trial_id) REFERENCES discovery_trials (trial_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_admission_id_fkey FOREIGN KEY (admission_id) REFERENCES source_admissions (admission_id);""",
    """ALTER TABLE discovery_qualifications ADD CONSTRAINT discovery_qualifications_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES vekl_resources (resource_id);""",
    """ALTER TABLE research_missions ADD CONSTRAINT research_missions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_missions ADD CONSTRAINT research_missions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_missions ADD CONSTRAINT research_missions_mission_id_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE research_cells ADD CONSTRAINT research_cells_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_cells ADD CONSTRAINT research_cells_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_cells ADD CONSTRAINT research_cells_mission_fkey FOREIGN KEY (research_mission_id) REFERENCES research_missions (research_mission_id);""",
    """ALTER TABLE research_packets ADD CONSTRAINT research_packets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_packets ADD CONSTRAINT research_packets_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_packets ADD CONSTRAINT research_packets_mission_fkey FOREIGN KEY (research_mission_id) REFERENCES research_missions (research_mission_id);""",
    """ALTER TABLE research_provider_runs ADD CONSTRAINT research_provider_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_provider_runs ADD CONSTRAINT research_provider_runs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_provider_runs ADD CONSTRAINT research_provider_runs_mission_fkey FOREIGN KEY (research_mission_id) REFERENCES research_missions (research_mission_id);""",
    """ALTER TABLE research_provider_runs ADD CONSTRAINT research_provider_runs_cell_fkey FOREIGN KEY (cell_id) REFERENCES research_cells (cell_id);""",
    """ALTER TABLE research_conflicts ADD CONSTRAINT research_conflicts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_conflicts ADD CONSTRAINT research_conflicts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_conflicts ADD CONSTRAINT research_conflicts_mission_fkey FOREIGN KEY (research_mission_id) REFERENCES research_missions (research_mission_id);""",
    """ALTER TABLE research_cursors ADD CONSTRAINT research_cursors_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE research_cursors ADD CONSTRAINT research_cursors_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE research_cursors ADD CONSTRAINT research_cursors_mission_fkey FOREIGN KEY (research_mission_id) REFERENCES research_missions (research_mission_id);""",
    """ALTER TABLE provider_readiness_snapshots ADD CONSTRAINT provider_readiness_snapshots_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE provider_readiness_snapshots ADD CONSTRAINT provider_readiness_snapshots_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE provider_readiness_snapshots ADD CONSTRAINT provider_readiness_capacity_fkey FOREIGN KEY (capacity_snapshot_id) REFERENCES provider_capacity_snapshots (snapshot_id);""",
    """ALTER TABLE execution_placement_decisions ADD CONSTRAINT execution_placement_decisions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE execution_placement_decisions ADD CONSTRAINT execution_placement_decisions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE execution_placement_decisions ADD CONSTRAINT execution_placement_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE execution_placement_decisions ADD CONSTRAINT execution_placement_task_fkey FOREIGN KEY (task_id) REFERENCES tasks (task_id);""",
    """ALTER TABLE execution_placement_decisions ADD CONSTRAINT execution_placement_readiness_fkey FOREIGN KEY (readiness_snapshot_id) REFERENCES provider_readiness_snapshots (readiness_snapshot_id);""",
    """ALTER TABLE capability_gates ADD CONSTRAINT capability_gates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE capability_gates ADD CONSTRAINT capability_gates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE capability_gate_probes ADD CONSTRAINT capability_gate_probes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE capability_gate_probes ADD CONSTRAINT capability_gate_probes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE capability_gate_probes ADD CONSTRAINT capability_gate_probes_gate_fkey FOREIGN KEY (gate_id) REFERENCES capability_gates (gate_id);""",
    """ALTER TABLE environment_certifications ADD CONSTRAINT environment_certifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE environment_certifications ADD CONSTRAINT environment_certifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE environment_certifications ADD CONSTRAINT environment_certifications_env_fkey FOREIGN KEY (environment_id) REFERENCES execution_environments (environment_id);""",
    """ALTER TABLE mission_steer_requests ADD CONSTRAINT mission_steer_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE mission_steer_requests ADD CONSTRAINT mission_steer_requests_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE mission_steer_requests ADD CONSTRAINT mission_steer_requests_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE steering_barriers ADD CONSTRAINT steering_barriers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE steering_barriers ADD CONSTRAINT steering_barriers_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE steering_barriers ADD CONSTRAINT steering_barriers_steer_fkey FOREIGN KEY (steer_id) REFERENCES mission_steer_requests (steer_id);""",
    """ALTER TABLE steering_barriers ADD CONSTRAINT steering_barriers_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_barrier_fkey FOREIGN KEY (barrier_id) REFERENCES steering_barriers (barrier_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_steer_fkey FOREIGN KEY (steer_id) REFERENCES mission_steer_requests (steer_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_run_fkey FOREIGN KEY (worker_run_id) REFERENCES worker_runs (run_id);""",
    """ALTER TABLE safe_boundary_receipts ADD CONSTRAINT safe_boundary_receipts_task_fkey FOREIGN KEY (task_id) REFERENCES tasks (task_id);""",
    """ALTER TABLE steering_impacts ADD CONSTRAINT steering_impacts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE steering_impacts ADD CONSTRAINT steering_impacts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE steering_impacts ADD CONSTRAINT steering_impacts_steer_fkey FOREIGN KEY (steer_id) REFERENCES mission_steer_requests (steer_id);""",
    """ALTER TABLE steering_impacts ADD CONSTRAINT steering_impacts_task_fkey FOREIGN KEY (task_id) REFERENCES tasks (task_id);""",
    """ALTER TABLE context_facts ADD CONSTRAINT context_facts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE context_facts ADD CONSTRAINT context_facts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE attention_candidates ADD CONSTRAINT attention_candidates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE attention_candidates ADD CONSTRAINT attention_candidates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE attention_candidates ADD CONSTRAINT attention_candidates_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE attention_candidates ADD CONSTRAINT attention_candidates_item_fkey FOREIGN KEY (attention_id) REFERENCES attention_items (attention_id);""",
    """ALTER TABLE attention_preferences ADD CONSTRAINT attention_preferences_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE attention_preferences ADD CONSTRAINT attention_preferences_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE automation_workflow_definitions ADD CONSTRAINT automation_workflow_definitions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE automation_workflow_definitions ADD CONSTRAINT automation_workflow_definitions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE automation_workflow_definitions ADD CONSTRAINT automation_workflow_definitions_descriptor_fkey FOREIGN KEY (derived_from_descriptor_id) REFERENCES automation_pattern_descriptors (descriptor_id);""",
    """ALTER TABLE automation_workflow_releases ADD CONSTRAINT automation_workflow_releases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE automation_workflow_releases ADD CONSTRAINT automation_workflow_releases_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE automation_workflow_releases ADD CONSTRAINT automation_workflow_releases_definition_fkey FOREIGN KEY (definition_id) REFERENCES automation_workflow_definitions (definition_id);""",
    """ALTER TABLE automation_run_grants ADD CONSTRAINT automation_run_grants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE automation_run_grants ADD CONSTRAINT automation_run_grants_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE automation_run_grants ADD CONSTRAINT automation_run_grants_release_fkey FOREIGN KEY (release_id) REFERENCES automation_workflow_releases (release_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_release_fkey FOREIGN KEY (release_id) REFERENCES automation_workflow_releases (release_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_task_fkey FOREIGN KEY (task_id) REFERENCES tasks (task_id);""",
    """ALTER TABLE automation_runs ADD CONSTRAINT automation_runs_lease_fkey FOREIGN KEY (capability_lease_id) REFERENCES capability_leases (lease_id);""",
    """ALTER TABLE browser_capability_sessions ADD CONSTRAINT browser_capability_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE browser_capability_sessions ADD CONSTRAINT browser_capability_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE browser_capability_sessions ADD CONSTRAINT browser_capability_sessions_mission_fkey FOREIGN KEY (mission_id) REFERENCES missions (mission_id);""",
    """ALTER TABLE browser_capability_sessions ADD CONSTRAINT browser_capability_sessions_task_fkey FOREIGN KEY (task_id) REFERENCES tasks (task_id);""",
    """ALTER TABLE browser_capability_sessions ADD CONSTRAINT browser_capability_sessions_lease_fkey FOREIGN KEY (capability_lease_id) REFERENCES capability_leases (lease_id);""",
    """ALTER TABLE external_effect_verifications ADD CONSTRAINT external_effect_verifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id);""",
    """ALTER TABLE external_effect_verifications ADD CONSTRAINT external_effect_verifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects (project_id);""",
    """ALTER TABLE external_effect_verifications ADD CONSTRAINT external_effect_verifications_effect_fkey FOREIGN KEY (effect_id) REFERENCES external_effects (effect_id);""",
)

_INDEXES = (
    """CREATE INDEX discovery_candidates_lifecycle_idx ON discovery_candidates (tenant_id, project_id, lifecycle_state);""",
    """CREATE INDEX research_cells_state_idx ON research_cells (research_mission_id, state);""",
    """CREATE INDEX provider_readiness_state_idx ON provider_readiness_snapshots (tenant_id, project_id, provider_id, readiness_state);""",
    """CREATE INDEX context_facts_subject_idx ON context_facts (tenant_id, project_id, subject, predicate);""",
    """CREATE INDEX external_effect_verifications_effect_idx ON external_effect_verifications (effect_id);""",
)

_ROW_LEVEL_SECURITY = (
    """ALTER TABLE discovery_candidates ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE discovery_candidates FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY discovery_candidates_tenant_isolation ON discovery_candidates USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE discovery_transitions ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE discovery_transitions FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY discovery_transitions_tenant_isolation ON discovery_transitions USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE discovery_observations ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE discovery_observations FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY discovery_observations_tenant_isolation ON discovery_observations USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE discovery_trials ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE discovery_trials FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY discovery_trials_tenant_isolation ON discovery_trials USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE discovery_qualifications ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE discovery_qualifications FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY discovery_qualifications_tenant_isolation ON discovery_qualifications USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_missions ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_missions FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_missions_tenant_isolation ON research_missions USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_cells ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_cells FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_cells_tenant_isolation ON research_cells USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_packets ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_packets FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_packets_tenant_isolation ON research_packets USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_provider_runs ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_provider_runs FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_provider_runs_tenant_isolation ON research_provider_runs USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_conflicts ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_conflicts FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_conflicts_tenant_isolation ON research_conflicts USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE research_cursors ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE research_cursors FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY research_cursors_tenant_isolation ON research_cursors USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE provider_readiness_snapshots ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE provider_readiness_snapshots FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY provider_readiness_snapshots_tenant_isolation ON provider_readiness_snapshots USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE execution_placement_decisions ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE execution_placement_decisions FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY execution_placement_decisions_tenant_isolation ON execution_placement_decisions USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE capability_gates ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE capability_gates FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY capability_gates_tenant_isolation ON capability_gates USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE capability_gate_probes ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE capability_gate_probes FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY capability_gate_probes_tenant_isolation ON capability_gate_probes USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE environment_certifications ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE environment_certifications FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY environment_certifications_tenant_isolation ON environment_certifications USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE mission_steer_requests ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE mission_steer_requests FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY mission_steer_requests_tenant_isolation ON mission_steer_requests USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE steering_barriers ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE steering_barriers FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY steering_barriers_tenant_isolation ON steering_barriers USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE safe_boundary_receipts ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE safe_boundary_receipts FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY safe_boundary_receipts_tenant_isolation ON safe_boundary_receipts USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE steering_impacts ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE steering_impacts FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY steering_impacts_tenant_isolation ON steering_impacts USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE context_facts ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE context_facts FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY context_facts_tenant_isolation ON context_facts USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE attention_candidates ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE attention_candidates FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY attention_candidates_tenant_isolation ON attention_candidates USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE attention_preferences ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE attention_preferences FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY attention_preferences_tenant_isolation ON attention_preferences USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE automation_workflow_definitions ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE automation_workflow_definitions FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY automation_workflow_definitions_tenant_isolation ON automation_workflow_definitions USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE automation_workflow_releases ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE automation_workflow_releases FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY automation_workflow_releases_tenant_isolation ON automation_workflow_releases USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE automation_run_grants ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE automation_run_grants FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY automation_run_grants_tenant_isolation ON automation_run_grants USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE automation_runs ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE automation_runs FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY automation_runs_tenant_isolation ON automation_runs USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE browser_capability_sessions ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE browser_capability_sessions FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY browser_capability_sessions_tenant_isolation ON browser_capability_sessions USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
    """ALTER TABLE external_effect_verifications ENABLE ROW LEVEL SECURITY;""",
    """ALTER TABLE external_effect_verifications FORCE ROW LEVEL SECURITY;""",
    """CREATE POLICY external_effect_verifications_tenant_isolation ON external_effect_verifications USING (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid)) WITH CHECK (tenant_id = CAST(current_setting('dde.tenant_id', true) AS uuid) AND project_id = CAST(current_setting('dde.project_id', true) AS uuid));""",
)

_TABLES = (
    "discovery_candidates",
    "discovery_transitions",
    "discovery_observations",
    "discovery_trials",
    "discovery_qualifications",
    "research_missions",
    "research_cells",
    "research_packets",
    "research_provider_runs",
    "research_conflicts",
    "research_cursors",
    "provider_readiness_snapshots",
    "execution_placement_decisions",
    "capability_gates",
    "capability_gate_probes",
    "environment_certifications",
    "mission_steer_requests",
    "steering_barriers",
    "safe_boundary_receipts",
    "steering_impacts",
    "context_facts",
    "attention_candidates",
    "attention_preferences",
    "automation_workflow_definitions",
    "automation_workflow_releases",
    "automation_run_grants",
    "automation_runs",
    "browser_capability_sessions",
    "external_effect_verifications",
)


_EXTERNAL_EFFECT_POSTCONDITION = (
    """ALTER TABLE external_effects ADD COLUMN postcondition_policy text""",
    """ALTER TABLE external_effects ADD COLUMN postcondition_state text""",
    """ALTER TABLE external_effects ADD COLUMN postcondition_verified_at timestamptz""",
    """ALTER TABLE external_effects ADD CONSTRAINT external_effects_postcondition_verified_check CHECK ((postcondition_state IS DISTINCT FROM 'VERIFIED') OR (postcondition_verified_at IS NOT NULL))""",
)

# A database built from base gets these columns from migration 0001's replay of the
# generated stage1 SQL, where the check is an inline unnamed constraint; one upgraded
# from 0040 gets them here with the explicit name. Both shapes must drop cleanly, and
# dropping the columns removes whichever constraint references them.
_EXTERNAL_EFFECT_POSTCONDITION_DOWN = (
    """ALTER TABLE external_effects DROP CONSTRAINT IF EXISTS external_effects_postcondition_verified_check""",
    """ALTER TABLE external_effects DROP COLUMN IF EXISTS postcondition_verified_at""",
    """ALTER TABLE external_effects DROP COLUMN IF EXISTS postcondition_state""",
    """ALTER TABLE external_effects DROP COLUMN IF EXISTS postcondition_policy""",
)


def _existing_0041_tables() -> set[str]:
    connection = op.get_bind()
    return {
        table
        for table in _TABLES
        if connection.execute(
            sa.text("SELECT to_regclass(:name)"), {"name": f"public.{table}"}
        ).scalar()
        is not None
    }


def _external_effect_postcondition_present() -> bool:
    connection = op.get_bind()
    return (
        connection.execute(
            sa.text(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = 'external_effects' "
                "AND column_name = 'postcondition_state'"
            )
        ).scalar()
        is not None
    )


def upgrade() -> None:
    # Migration 0001 replays the generated schemas/sql/0001_stage1.sql, which already
    # contains every table below. A database built from base therefore arrives here
    # with them present; one upgraded from an older head does not. Same convention as
    # migration 0040: skip when complete, refuse a partial schema.
    existing = _existing_0041_tables()
    if existing:
        if existing != set(_TABLES):
            missing = sorted(set(_TABLES) - existing)
            raise RuntimeError(
                "partial cross-system operational intelligence schema detected before "
                f"migration 0041; missing tables: {', '.join(missing)}"
            )
    else:
        for statement in _CREATE_TABLES:
            op.execute(statement)
        for statement in _FOREIGN_KEYS:
            op.execute(statement)
        for statement in _INDEXES:
            op.execute(statement)
        for statement in _ROW_LEVEL_SECURITY:
            op.execute(statement)
    if not _external_effect_postcondition_present():
        for statement in _EXTERNAL_EFFECT_POSTCONDITION:
            op.execute(statement)


def downgrade() -> None:
    if _external_effect_postcondition_present():
        for statement in _EXTERNAL_EFFECT_POSTCONDITION_DOWN:
            op.execute(statement)
    for table in reversed(_TABLES):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
