"""SQLAlchemy Core mappings for domain-neutral Source Intelligence
and the automation corpus."""

from __future__ import annotations

from sqlalchemy import TIMESTAMP, Column, Integer, Table, Text, UniqueConstraint, Uuid
from sqlalchemy.dialects.postgresql import JSONB

from engine.studio.tables import metadata

source_records = Table(
    "source_records",
    metadata,
    Column("source_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("provider_key", Text, nullable=False),
    Column("display_name", Text, nullable=False),
    Column("source_domain", Text, nullable=False),
    Column("source_class", Text, nullable=False),
    Column("source_kind", Text, nullable=False),
    Column("source_trust", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("policy_revision", Text, nullable=False),
    Column("config", JSONB, nullable=False),
    Column("revoked_at", TIMESTAMP(timezone=True)),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint("project_id", "provider_key"),
)

source_artifacts = Table(
    "source_artifacts",
    metadata,
    Column("artifact_id", Uuid(as_uuid=True), primary_key=True),
    Column("source_id", Uuid(as_uuid=True), nullable=False),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("parent_artifact_id", Uuid(as_uuid=True)),
    Column("artifact_kind", Text, nullable=False),
    Column("provider_artifact_key", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("source_uri", Text),
    Column("revision", Text, nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("content_object_ref", Text),
    Column("content_object_backend", Text),
    Column("content_size_bytes", Integer),
    Column("media_type", Text),
    Column("metadata", JSONB, nullable=False),
    Column("provenance", JSONB, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint("source_id", "provider_artifact_key", "revision", "content_hash"),
)

source_admissions = Table(
    "source_admissions",
    metadata,
    Column("admission_id", Uuid(as_uuid=True), primary_key=True),
    Column("source_id", Uuid(as_uuid=True), nullable=False),
    Column("artifact_id", Uuid(as_uuid=True), nullable=False),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("content_hash", Text, nullable=False),
    Column("compiler_version", Text, nullable=False),
    Column("policy_version", Text, nullable=False),
    Column("qualification_domain", Text, nullable=False),
    Column("qualification_profile", Text, nullable=False),
    Column("state", Text, nullable=False),
    Column("source_trust", Text, nullable=False),
    Column("reuse_class", Text, nullable=False),
    Column("analysis", JSONB, nullable=False),
    Column("hard_failures", JSONB, nullable=False),
    Column("validation_obligations", JSONB, nullable=False),
    Column("provenance", JSONB, nullable=False),
    Column("security_state", Text, nullable=False),
    Column("license_state", Text, nullable=False),
    Column("provenance_state", Text, nullable=False),
    Column("sanitization_state", Text, nullable=False),
    Column("injection_state", Text, nullable=False),
    Column("revoked_at", TIMESTAMP(timezone=True)),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint(
        "artifact_id", "content_hash", "compiler_version", "policy_version"
    ),
)

automation_corpus_snapshots = Table(
    "automation_corpus_snapshots",
    metadata,
    Column("snapshot_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("source_id", Uuid(as_uuid=True), nullable=False),
    Column("artifact_id", Uuid(as_uuid=True), nullable=False),
    Column("repository", Text, nullable=False),
    Column("commit_sha", Text, nullable=False),
    Column("archive_sha256", Text, nullable=False),
    Column("acquisition_policy_version", Text, nullable=False),
    Column("acquisition_policy_hash", Text, nullable=False),
    Column("acquisition_effect_id", Uuid(as_uuid=True), nullable=False),
    Column("acquired_at", TIMESTAMP(timezone=True), nullable=False),
    Column("compressed_bytes", Integer, nullable=False),
    Column("expanded_bytes", Integer, nullable=False),
    Column("workflow_count", Integer, nullable=False),
    Column("object_ref", Text, nullable=False),
    Column("object_backend", Text, nullable=False),
    Column("state", Text, nullable=False),
    Column("license_state", Text, nullable=False),
    Column("license_path", Text),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint("project_id", "repository", "commit_sha", "archive_sha256"),
)

automation_workflow_artifacts = Table(
    "automation_workflow_artifacts",
    metadata,
    Column("workflow_artifact_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("snapshot_id", Uuid(as_uuid=True), nullable=False),
    Column("artifact_id", Uuid(as_uuid=True), nullable=False),
    Column("path", Text, nullable=False),
    Column("raw_hash", Text, nullable=False),
    Column("raw_size_bytes", Integer, nullable=False),
    Column("parser_state", Text, nullable=False),
    Column("source_metadata", JSONB, nullable=False),
    Column("state", Text, nullable=False),
    Column("findings", JSONB, nullable=False),
    Column("pattern_lineage_id", Text),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint("snapshot_id", "path", "raw_hash"),
)

automation_pattern_descriptors = Table(
    "automation_pattern_descriptors",
    metadata,
    Column("descriptor_id", Uuid(as_uuid=True), primary_key=True),
    Column("tenant_id", Uuid(as_uuid=True), nullable=False),
    Column("project_id", Uuid(as_uuid=True), nullable=False),
    Column("snapshot_id", Uuid(as_uuid=True), nullable=False),
    Column("artifact_id", Uuid(as_uuid=True), nullable=False),
    Column("pattern_lineage_id", Text, nullable=False),
    Column("pattern_revision_hash", Text, nullable=False),
    Column("archetype", Text, nullable=False),
    Column("guidance_polarity", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("summary", Text, nullable=False),
    Column("trigger_classes", JSONB, nullable=False),
    Column("action_classes", JSONB, nullable=False),
    Column("integration_classes", JSONB, nullable=False),
    Column("control_flow", JSONB, nullable=False),
    Column("resilience_controls", JSONB, nullable=False),
    Column("security_controls", JSONB, nullable=False),
    Column("observability_controls", JSONB, nullable=False),
    Column("failure_modes", JSONB, nullable=False),
    Column("required_capabilities", JSONB, nullable=False),
    Column("stack_constraints", JSONB, nullable=False),
    Column("source_workflow_refs", JSONB, nullable=False),
    Column("source_workflow_hashes", JSONB, nullable=False),
    Column("parser_version", Text, nullable=False),
    Column("sanitizer_version", Text, nullable=False),
    Column("scanner_version", Text, nullable=False),
    Column("descriptor_hash", Text, nullable=False),
    Column("topology_hash", Text, nullable=False),
    Column("topology_compiler_version", Text, nullable=False),
    Column("security_findings", JSONB, nullable=False),
    Column("pii_findings", JSONB, nullable=False),
    Column("secret_findings", JSONB, nullable=False),
    Column("prompt_findings", JSONB, nullable=False),
    Column("implementation_guidance", JSONB, nullable=False),
    Column("anti_pattern_notes", JSONB, nullable=False),
    Column("auth_pattern", JSONB, nullable=False),
    Column("retry_error_pattern", JSONB, nullable=False),
    Column("idempotency_pattern", JSONB, nullable=False),
    Column("persistence_pattern", JSONB, nullable=False),
    Column("worker_safe_capsule", JSONB, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False),
    Column("updated_at", TIMESTAMP(timezone=True), nullable=False),
    UniqueConstraint("project_id", "pattern_lineage_id", "pattern_revision_hash"),
    UniqueConstraint("project_id", "descriptor_hash"),
)
